<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CreateUserTable extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'nip' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Nomor Induk Pegawai',
            ],
            'no_sap' => [
                'type'       => 'INT',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Nomor SAP (jika ada)',
            ],
            'password' => [
                'type'       => 'VARCHAR',
                'constraint' => 150,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Password user (hashed)',
            ],
            'nama_user' => [
                'type'       => 'VARCHAR',
                'constraint' => 150,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Nama lengkap user',
            ],
            'foto_profile' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Path/URL foto profil',
            ],
            'tgl_lahir' => [
                'type'       => 'DATE',
                'null'       => false,
                'default'    => '1989-10-25',
                'comment'    => 'Tanggal lahir user',
            ],
            'tempat_lahir' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Tempat lahir user',
            ],
            'jenis_kelamin' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Jenis kelamin user',
            ],
            'agama' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Agama user',
            ],
            'status_perkawinan' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Status perkawinan user',
            ],
            'grade' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Grade user',
            ],
            'tgl_grade_terakhir' => [
                'type'       => 'DATE',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal terakhir user mendapat grade',
            ],
            'email_korpo' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Email korporat user',
            ],
            'email_non' => [
                'type'       => 'VARCHAR',
                'constraint' => 150,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Email non korporat user',
            ],
            'no_hp' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Nomor HP user',
            ],
            'no_ktp' => [
                'type'       => 'INT',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Nomor KTP user',
            ],
            'npwp' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Nomor NPWP user',
            ],
            'alamat' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Alamat lengkap user',
            ],
            'kota_alamat' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Kota alamat user',
            ],
            'tgl_masuk' => [
                'type'       => 'DATE',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal masuk perusahaan',
            ],
            'tgl_capeg' => [
                'type'       => 'DATE',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal jadi calon pegawai',
            ],
            'tgl_peg_tetap' => [
                'type'       => 'DATE',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal diangkat pegawai tetap',
            ],
            'sebutan_jabatan' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => false,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Nama sebutan jabatan user',
            ],
            'jenjab' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Jenjang jabatan',
            ],
            'pog' => [
                'type'       => 'VARCHAR',
                'constraint' => 10,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'POG',
            ],
            'kode_org_unit' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Kode organisasi unit',
            ],
            'nama_org_unit' => [
                'type'       => 'VARCHAR',
                'constraint' => 1000,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Nama organisasi unit',
            ],
            'start_date_jabatan' => [
                'type'       => 'DATE',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal mulai jabatan',
            ],
            'profesi_jabatan' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Profesi jabatan user',
            ],
            'htd_area' => [
                'type'       => 'INT',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Kode area HTD',
            ],
            'unit_induk' => [
                'type'       => 'INT',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Kode unit induk',
            ],
            'unit_pelaksana' => [
                'type'       => 'INT',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Kode unit pelaksana',
            ],
            'sub_unit_pelaksana' => [
                'type'       => 'INT',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Kode sub unit pelaksana',
            ],
            'role_peg' => [
                'type'       => "ENUM('1','0')",
                'null'       => false,
                'default'    => '1',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role pegawai (1=aktif,0=nonaktif)',
            ],
            'role_htd' => [
                'type'       => "ENUM('0','1','2','3','4')",
                'null'       => false,
                'default'    => '4',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => '0=staff, 1=vp, 2=msb, 3=asman, 4=non htd',
            ],
            'role_admin' => [
                'type'       => "ENUM('1','0')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin',
            ],
            'role_komite' => [
                'type'       => "ENUM('1','0')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role komite',
            ],
            'role_adm_acc' => [
                'type'       => "ENUM('1','0')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin accounting',
            ],
            'role_adm_eclinic' => [
                'type'       => "ENUM('1','0')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin eClinic',
            ],
            'role_adm_hi' => [
                'type'       => "ENUM('1','0')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin HR/HI',
            ],
            'role_adm_org' => [
                'type'       => "ENUM('0','1')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin organisasi',
            ],
            'role_adm_kinerja' => [
                'type'       => "ENUM('0','1')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin kinerja',
            ],
            'role_adm_diklat' => [
                'type'       => "ENUM('0','1')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin diklat',
            ],
            'role_adm_sertifikasi' => [
                'type'       => "ENUM('0','1')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Role admin sertifikasi',
            ],
            'ket_aktif' => [
                'type'       => "ENUM('0','1')",
                'null'       => false,
                'default'    => '0',
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Keterangan aktif',
            ],
            'tx_esgrp' => [
                'type'       => 'VARCHAR',
                'constraint' => 300,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'ESGRP',
            ],
            'tx_insjab' => [
                'type'       => 'VARCHAR',
                'constraint' => 300,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Insjab',
            ],
            'tx_grpjab' => [
                'type'       => 'VARCHAR',
                'constraint' => 300,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Grup jabatan',
            ],
            'kd_posisi' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Kode posisi',
            ],
            'jbtn' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Jabatan',
            ],
            'tglm_posisi' => [
                'type'       => 'DATE',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal mulai posisi',
            ],
            'jn_pddkkah' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Jenis pendidikan terakhir',
            ],
            'tx_nikah' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Status pernikahan',
            ],
            'kd_posatsn' => [
                'type'       => 'VARCHAR',
                'constraint' => 300,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Kode POS ATSN',
            ],
            'tx_posatsn' => [
                'type'       => 'VARCHAR',
                'constraint' => 1000,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'POS ATSN',
            ],
            'tx_org_01' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 01',
            ],
            'tx_org_02' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 02',
            ],
            'tx_org_03' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 03',
            ],
            'tx_org_04' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 04',
            ],
            'tx_org_05' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 05',
            ],
            'tx_org_06' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 06',
            ],
            'tx_org_07' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 07',
            ],
            'tx_org_08' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 08',
            ],
            'tx_org_09' => [
                'type'       => 'VARCHAR',
                'constraint' => 500,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Organisasi level 09',
            ],
            'jabatan_lengkap' => [
                'type'       => 'VARCHAR',
                'constraint' => 1000,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Jabatan lengkap',
            ],
            'hukdis' => [
                'type'       => 'VARCHAR',
                'constraint' => 300,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Hukuman disiplin',
            ],
            'tgl_selesai_hukdis' => [
                'type'       => 'DATE',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal selesai hukdis',
            ],
            'pap' => [
                'type'       => 'VARCHAR',
                'constraint' => 300,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'PAP',
            ],
            'regional' => [
                'type'       => 'VARCHAR',
                'constraint' => 300,
                'null'       => true,
                'default'    => null,
                'collation'  => 'utf8mb3_unicode_ci',
                'comment'    => 'Regional',
            ],
            'created_at' => [
                'type'       => 'DATETIME',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal dibuat',
            ],
            'updated_at' => [
                'type'       => 'DATETIME',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal diupdate',
            ],
            'deleted_at' => [
                'type'       => 'DATETIME',
                'null'       => true,
                'default'    => null,
                'comment'    => 'Tanggal dihapus',
            ],
        ]);

        $this->forge->addKey('nip', true);

        $this->forge->createTable('user', true, [
            'ENGINE'  => 'InnoDB',
            'DEFAULT CHARSET' => 'utf8mb3',
            'COLLATE' => 'utf8mb3_unicode_ci',
            'comment' => 'Tabel data user',
        ]);
    }

    public function down()
    {
        $this->forge->dropTable('user');
    }
}
