<?php

namespace App\Models;

use CodeIgniter\Model;

class UserModel extends Model
{
    protected $table = 'user';
    protected $primaryKey = 'nip';
    protected $allowedFields = [
        'nip',
        'no_sap',
        'password',
        'nama_user',
        'foto_profile',
        'tgl_lahir',
        'tempat_lahir',
        'jenis_kelamin',
        'agama',
        'status_perkawinan',
        'grade',
        'tgl_grade_terakhir',
        'email_korpo',
        'email_non',
        'no_hp',
        'no_ktp',
        'npwp',
        'alamat',
        'kota_alamat',
        'tgl_masuk',
        'tgl_capeg',
        'tgl_peg_tetap',
        'sebutan_jabatan',
        'jenjab',
        'pog',
        'kode_org_unit',
        'nama_org_unit',
        'start_date_jabatan',
        'profesi_jabatan',
        'htd_area',
        'unit_induk',
        'unit_pelaksana',
        'sub_unit_pelaksana',
        'role_peg',
        'role_htd',
        'role_admin',
        'role_komite',
        'role_adm_acc',
        'role_adm_eclinic',
        'role_adm_hi',
        'role_adm_org',
        'role_adm_kinerja',
        'role_adm_diklat',
        'role_adm_sertifikasi',
        'ket_aktif',
        'tx_esgrp',
        'tx_jnsjab',
        'tx_grpjab',
        'kd_posisi',
        'jbtn',
        'tglm_posisi',
        'jn_pddkakh',
        'tx_nikah',
        'kd_posatsn',
        'tx_posatsn',
        'tx_org_01',
        'tx_org_02',
        'tx_org_03',
        'tx_org_04',
        'tx_org_05',
        'tx_org_06',
        'tx_org_07',
        'tx_org_08',
        'tx_org_09',
        'jabatan_lengkap',
        'hukdis',
        'tgl_selesai_hukdis',
        'pap',
        'regional',
        'created_at',
        'updated_at',
        'deleted_at'
    ];
}
